- name: Read-write git checkout from github
  ansible.builtin.git:
    repo: https://github.com/ritoooo/dots2.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    bare: true

- name: Git checkout
  ansible.builtin.shell: |
    echo "alias dots='/usr/bin/git --git-dir=\$HOME/.dotfiles/ --work-tree=\$HOME'" >> ~/.bashrc
    source ~/.bashrc
